---
title: "PEC1_V2"
author: "Julian Sanchez Bautista"
date: "5/1/2020"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GEOquery)
gset <- getGEO("GSE32496", GSEMatrix =TRUE, getGPL=FALSE)
if (length(gset) > 1) idx <- grep("GPL570", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]
```

```{r}
dev.new(width=4+dim(gset)[[2]]/5, height=6)
par(mar=c(2+round(max(nchar(sampleNames(gset)))/2),4,2,1))
title <- paste ("GSE32496", '/', annotation(gset), " selected samples", sep ='')
boxplot(exprs(gset), boxwex=0.7, notch=T, main=title, outline=FALSE, las=2)
```

```{r}
library(arrayQualityMetrics)
```


```{r}
library(ggplot2)
library(ggrepel)
```

```{r}
plotPCA3 <- function (datos, labels, factor, title, scale,colores, size = 1.5, glineas = 0.25) {
  data <- prcomp(t(datos),scale=scale)
  dataDf <- data.frame(data$x)
  Group <- factor
  loads <- round(data$sdev^2/sum(data$sdev^2)*100,1)
  p1 <- ggplot(dataDf,aes(x=PC1, y=PC2)) +
    theme_classic() +
    geom_hline(yintercept = 0, color = "gray70") +
    geom_vline(xintercept = 0, color = "gray70") +
    geom_point(aes(color = Group), alpha = 0.55, size = 3) +
    coord_cartesian(xlim = c(min(data$x[,1])-5,max(data$x[,1])+5)) +
    scale_fill_discrete(name = "Group")
  p1 + geom_text_repel(aes(y = PC2 + 0.25, label = labels),segment.size = 0.25, size = size) + 
    labs(x = c(paste("PC1",loads[1],"%")),y=c(paste("PC2",loads[2],"%"))) +  
    ggtitle(paste("Principal Component Analysis for: ",title,sep=" "))+ 
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_color_manual(values=colores)
}
```

```{r}
plotPCA3(exprs(gset), labels = gset$title, factor = gset$characteristics_ch1.1, 
        title="Datos", scale = FALSE, size = 3, 
        colores = c("red", "blue", "yellow"))
```

```{r}
class(gset)
```

```{r}
library(limma)
designMat<- model.matrix(~0+gset$characteristics_ch1.1, pData(gset))
colnames(designMat) <- c("Aza.dC", "Aza.dC.TSA", "untreated")
print(designMat)
```

```{r}
cont.matrix <- makeContrasts (Aza.dCvsAza.dc.TSA = Aza.dC-Aza.dC.TSA,
                              Aza.dCvsuntreated = Aza.dC-untreated,
                              Aza.dC.TSAvsuntreated = Aza.dC.TSA-untreated,
                              INT = (Aza.dC-Aza.dC.TSA)-(Aza.dC-untreated)-(Aza.dC.TSA-untreated),
                              levels=designMat)
print(cont.matrix)
```

```{r}
library(limma)
fit<-lmFit(gset, designMat)
fit.main<-contrasts.fit(fit, cont.matrix)
fit.main<-eBayes(fit.main)
class(fit.main)
```

```{r}
topTab_Aza.dCvsAza.dc.TSA <- topTable (fit.main, number=nrow(fit.main), coef="Aza.dCvsAza.dc.TSA", adjust="fdr") 
head(topTab_Aza.dCvsAza.dc.TSA)
```

```{r}
topTab_Aza.dCvsuntreated <- topTable (fit.main, number=nrow(fit.main), coef="Aza.dCvsuntreated", adjust="fdr") 
head(topTab_Aza.dCvsuntreated)
```

```{r}
topTab_Aza.dC.TSAvsuntreated <- topTable (fit.main, number=nrow(fit.main), coef="Aza.dC.TSAvsuntreated", adjust="fdr") 
head(topTab_Aza.dC.TSAvsuntreated)
```

```{r}
topTab_INT  <- topTable (fit.main, number=nrow(fit.main), coef="INT", adjust="fdr") 
head(topTab_INT)
```

```{r}
annotatedTopTable <- function(topTab, anotPackage)
 {
   topTab <- cbind(PROBEID=rownames(topTab), topTab)
   myProbes <- rownames(topTab)
   thePackage <- eval(parse(text = anotPackage))
   geneAnots <- select(thePackage, myProbes, c("SYMBOL", "ENTREZID", "GENENAME"))
   annotatedTopTab<- merge(x=geneAnots, y=topTab, by.x="PROBEID", by.y="PROBEID")
 return(annotatedTopTab)
 }
```

```{r}
require(hgu133plus2.db)
topAnnotated_topTab_Aza.dCvsAza.dc.TSA <- annotatedTopTable(topTab_Aza.dCvsAza.dc.TSA,
                                          anotPackage="hgu133plus2.db")
```

```{r}
topAnnotated_topTab_Aza.dCvsuntreated <- annotatedTopTable(topTab_Aza.dCvsuntreated,
 anotPackage="hgu133plus2.db")
```

```{r}
topAnnotated_topTab_Aza.dC.TSAvsuntreated <- annotatedTopTable(topTab_Aza.dC.TSAvsuntreated,
 anotPackage="hgu133plus2.db")
```

```{r}
topAnnotated_topTab_INT <- annotatedTopTable(topTab_INT,
 anotPackage="hgu133plus2.db")
```

```{r}
library(hgu133plus2.db)
geneSymbols <- select(hgu133plus2.db, rownames(fit.main), c("SYMBOL"))
SYMBOLS<- geneSymbols$SYMBOL
volcanoplot(fit.main, coef=1, highlight=4, names=SYMBOLS, 
            main=paste("Differentially expressed genes"))
abline(v=c(-1,1))
```
##Multiples comparaciones
```{r}
library(limma)
res<-decideTests(fit.main, method="separate", adjust.method="fdr", p.value=0.1, lfc=1)
```
```{r}
sum.res.rows<-apply(abs(res),1,sum)
res.selected<-res[sum.res.rows!=0,] 
print(summary(res))
```

```{r}
vennDiagram (res.selected[,1:3], cex=0.9)
title("Genes in common between the three comparisons\n Genes selected with FDR < 0.1 and logFC > 1")
```

##Analisis de signifacion biologica
```{r}
listOfTables <- list(Aza.dCvsAza.dc.TSA = topTab_Aza.dCvsAza.dc.TSA, 
                     Aza.dCvsuntreated  = topTab_Aza.dCvsuntreated,
                     Aza.dC.TSAvsuntreated = topTab_Aza.dC.TSAvsuntreated,
                     INT = topTab_INT)
listOfSelected <- list()
for (i in 1:length(listOfTables)){
topTab <- listOfTables[[i]]
whichGenes<-topTab["adj.P.Val"]<0.15
selectedIDs <- rownames(topTab)[whichGenes]
EntrezIDs<- select(hgu133plus2.db, selectedIDs, c("ENTREZID"))
EntrezIDs <- EntrezIDs$ENTREZID
listOfSelected[[i]] <- EntrezIDs
names(listOfSelected)[i] <- names(listOfTables)[i]
}
sapply(listOfSelected, length)
```


```{r}
library(clusterProfiler)
ck <- compareCluster(geneCluster = listOfSelected, fun = "enrichKEGG")
```

```{r}
dotplot(ck)
```
```{r}
cnetplot(ck, categorySize = "geneNum", schowCategory = 15, 
        vertex.label.cex = 0.75)

```




